module.exports = {
  ADD_AUTHOR: 1,
  UPLOAD_FILE: 2,
  SUBMITTED: 3,
  IN_REVIEW: 4,
  REVIEW_DONE: 5,
  SENT_BACK_TO_AUTHOR: 6,
  RETURNED_PAPER: 7,
  NEED_REVISION: 8,
  IN_REVISION: 9,
  REVISION_DONE: 10,
  COMPLETED: 11,
  REJECTED: 12,
}